[package]
name = "Projet_ml_mma"
version = "0.1.0"
edition = "2021"
opencv = "0.80.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
<<<<<<< HEAD
rusty-machine = "0.5.4"
=======
ndarray = "0.15.4"
image = "0.23.14"
>>>>>>> 1b99c7dbefc2e75972f2656bd668b0e163e558b5
