[package]
name = "Projet_ml_mma"
version = "0.1.0"
edition = "2021"
opencv = "0.80.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
rusty-machine = "0.5.4"