[package]
name = "linear_modele"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.8" }

[lib]
crate-type = ["cdylib"]
path = "../src/ml_roseblatt.rs"